In [6]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt 
import seaborn as sns

df = pd.read_csv("../data/training_data/mixed_demographics.csv")
df.shape

(900, 9)

In [7]:
df.head()

,index,MI,age,BMI,height,weight,diastolic_BP,systolic_BP,sex
0,0,healthy,62.593012,25.312186,161.647749,64.949107,76.057670,137.765801,False
1,1,healthy,58.037959,32.100795,172.543391,94.715477,84.272113,143.459426,False
2,2,pMI,65.840496,26.099055,166.521430,71.650562,75.340419,137.100866,False
3,3,pMI,68.518300,27.672836,166.176884,75.779414,75.697258,140.518093,True
4,4,healthy,55.591381,27.266429,161.314821,70.185424,79.973837,133.740780,False

In [8]:
df["MI"].value_counts()

MI
healthy    452
pMI        448
Name: count, dtype: int64

In [9]:
df.isna().sum()

index           0
MI              0
age             0
BMI             0
height          0
weight          0
diastolic_BP    0
systolic_BP     0
sex             0
dtype: int64

In [11]:
features = [

    "age", 
    "BMI", 
    "height", 
    "weight", 
    "diastolic_BP",
    "systolic_BP", 
    "sex"
]

X = df[features]
y = df['MI'].map({
    "healthy":0,
    "pMI":1
})

X.head()

,age,BMI,height,weight,diastolic_BP,systolic_BP,sex
0,62.593012,25.312186,161.647749,64.949107,76.057670,137.765801,False
1,58.037959,32.100795,172.543391,94.715477,84.272113,143.459426,False
2,65.840496,26.099055,166.521430,71.650562,75.340419,137.100866,False
3,68.518300,27.672836,166.176884,75.779414,75.697258,140.518093,True
4,55.591381,27.266429,161.314821,70.185424,79.973837,133.740780,False

In [12]:
y.head()

0    0
1    0
2    1
3    1
4    0
Name: MI, dtype: int64